### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PrestonAshton** [dukus/digiCamControl#114]
Hi! I am looking to see if there is any documentation for this library published by you on Nuget. I want to make my own app for my own needs and I was wondering if there are any basic guides for camera detection and how the library works. Any help will be appreciated.

Thank You

-Preston

**Comment by dukus** [comment]
There is a example project : https://github.com/dukus/digiCamControl/tree/master/CameraControl.Devices.Example 
In the near  future i will try to make a simple documentation.

**Comment by PrestonAshton** [comment]
Thank you! :smile:

**Comment by PrestonAshton** [comment]
I've been doing some work on stuff and I'm now getting an error:

An exception of type 'System.IO.FileNotFoundException' occurred in PortableDeviceLib.dll but was not handled in user code

`Additional information: Could not load file or assembly 'Interop.PortableDeviceApiLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

Do you know what this is caused by and how I can fix it? Am I missing some SDK files or something?

My camera is a Nikon D3200.

Thanks for any support and support thus far.

**Comment by dukus** [comment]
Seems it is some problems with nuget  package, i will try to fix today or tomorrow

**Comment by PrestonAshton** [comment]
Ah OK, thank you. I guess I should compile it myself?

**Comment by dukus** [comment]
Yes then will work

**Comment by PrestonAshton** [comment]
Thanks again for the quick response :sweat_smile:

**Comment by dukus** [comment]
If you have any question or suggestion just let me know

**Comment by PrestonAshton** [comment]
Just in time actually, my captureComplete function isn't working.

I'm adding a callback here
            currentCamera.PhotoCaptured += captureComplete;

but it never gets called once I take the shot with

            currentCamera.CapturePhotoNoAf();

Thanks for all your help so far, I really appreciate it.

**Comment by dukus** [comment]
Try to use:

DeviceManager.PhotoCaptured += DeviceManager_PhotoCaptured;

**Comment by PrestonAshton** [comment]
It's still not working

My code is here:

https://github.com/PrestonAshton/bCameraControl

**Comment by dukus** [comment]
The DeviceManager.PhotoCaptured += captureComplete; should be called once in Form1() constructor 

The D3200 cant record directly to pc so you should set currentCamera.CaptureInSdRam = false; in connectCamera()

Just now i can't try you code but tomorrow i will make time for it

**Comment by PrestonAshton** [comment]
I set that and I have done that, it still makes no difference. It seems like the first line of the callback gets triggered;
http://puu.sh/jguNw/91dbab01c7.png

but nothing ever gets added to my listview and none of the code following it is triggered.

Thanks for your help so far. :smile:

**Comment by PrestonAshton** [comment]
Looking through the error log:

    Event queue processing error    at System.Windows.Forms.Control.get_Handle()
       at System.Windows.Forms.Control.OnEnabledChanged(EventArgs e)
       at System.Windows.Forms.ButtonBase.OnEnabledChanged(EventArgs e)
       at System.Windows.Forms.Control.set_Enabled(Boolean value)
       at bCameraControl.Form1.captureComplete(Object sender, PhotoCapturedEventArgs e) in     J:\foo\bCameraControl\bCameraControl\Form1.cs:line 102
       at CameraControl.Devices.CameraDeviceManager.cameraDevice_PhotoCaptured(Object sender, PhotoCapturedEventArgs eventArgs) in e:\devel\vs2010\CameraControl\CameraControl.Devices\CameraDeviceManager.cs:line 302
   at CameraControl.Devices.BaseCameraDevice.OnPhotoCapture(Object sender,     PhotoCapturedEventArgs args) in     e:\devel\vs2010\CameraControl\CameraControl.Devices\BaseCameraDevice.cs:line 442
       at CameraControl.Devices.Nikon.NikonBase.GetEvent(Object state) in     e:\devel\vs2010\CameraControl\CameraControl.Devices\Nikon\NikonBase.cs:line 1763

**Comment by dukus** [comment]
The library run a event listener in a separated thread so event generated by it also run in a separated thread so if you want to interact with winform controls you should use :  BeginInvoke

For your case:
```C#
        public void captureComplete(object sender, PhotoCapturedEventArgs e)
        {
            MethodInvoker method = delegate
            {
                if (autoBracketingEnabled.Checked)
                {
                    if (nextBracket != brackets.Length)
                    {
                        nextBracket++;
                        bracket(brackets[nextBracket]);
                    }
                    else
                    {
                        captureButton.Enabled = true;
                    }
                }
                else
                {
                    captureButton.Enabled = true;
                }
            };
            if (InvokeRequired)
                BeginInvoke(method);
            else
                method.Invoke();
        }
```

**Comment by PrestonAshton** [comment]
Thanks for the reply, you can tell I'm not a C# developer.
It's working now! :smile: 

Thanks for your continued support.

**Comment by PrestonAshton** [comment]
I do not think I am setting the exposure compensation correctly however as it is not working. Is there a proper way to do this?

**Comment by dukus** [comment]
The currentCamera.ExposureCompensation.SetValue() should use string values from 
currentCamera.ExposureCompensation.Values list. So you can use something like :
currentCamera.ExposureCompensation.SetValue("+1")

**Comment by PrestonAshton** [comment]
Thank you! It's working! :smile:

**Comment by PrestonAshton** [comment]
Is there way to make it take the shots quicker, as in not wait for it to save on the SD but wait for the buffer?

**Comment by dukus** [comment]
You can try to call capture in row without using events, but some cases may fail if the device is busy (the writing to card isn't cause device busy)

            currentCamera.ExposureCompensation.SetValue("+1");
            currentCamera.CapturePhotoNoAf();
            currentCamera.ExposureCompensation.SetValue("+2");
            currentCamera.CapturePhotoNoAf();

**Comment by PrestonAshton** [comment]
Yeah I'm getting an 'Access Denied'

**Comment by PrestonAshton** [comment]
Doesn't even want to take 3 photos on a D7000, it just takes one...

**Comment by PrestonAshton** [comment]
I can set the camera on 'Burst Mode' through PTP with 

currentCamera.AdvancedProperties[2].SetValue("3.0");

unfortunately I cannot find a way to change exposure through this. Although it does take the pictures fast :p:

**Comment by dukus** [comment]
You can't set any properties during burst capture

**Comment by PrestonAshton** [comment]
I can set the camera to continuous shooting mode and it works fine!
                            currentCamera.AdvancedProperties[3].SetValue(currentCamera.AdvancedProperties[3].Values[1]);
    currentCamera.ExposureCompensation.SetValue(exposures[i]);
    currentCamera.CapturePhotoNoAf();

This works for me and has made it so that braceting works amazingly. Is there a better way to do this?

**Comment by PrestonAshton** [comment]
Its not working randomly out of the blue now... Ugh...

**Comment by PrestonAshton** [comment]
Do you have any ideas why it sometimes doesn't work and sometimes it does? It more often than not doesn't... :confused:

**Comment by PrestonAshton** [comment]
I have fixed it by doing:

            currentCamera.CaptureInSdRam = false;
            for (int i = 0; i < exposures.Length; i++)
            {
                try
                {
                    captureButton.Enabled = false;
                    currentCamera.AdvancedProperties[3].SetValue(2);
                    currentCamera.ExposureCompensation.SetValue(exposures[i]);
                    currentCamera.CapturePhotoNoAf();
                    currentCamera.CaptureInSdRam = true;
                }
                catch
                {
                    i = i - 1;
                }
            }
            currentCamera.ExposureCompensation.SetValue("0.0");
            currentCamera.CaptureInSdRam = false;

**Comment by PrestonAshton** [comment]
What does CaptureInSdRam do?

**Comment by dukus** [comment]
Will capture the image in camera Ram not in card if is true, but you take care to download the image from camera because the buffer will fill up.
https://github.com/dukus/digiCamControl/blob/master/CameraControl.Devices.Example/Form1.cs#L97

**Comment by PrestonAshton** [comment]
Hmm, it just makes my camera freeze... Did you say the D3200 doesn't support it?

**Comment by dukus** [comment]
Yes the D3200 not support it

**Comment by PrestonAshton** [comment]
Before I give it a go, would it work on a D7000?

**Comment by dukus** [comment]
Yes

**Comment by PrestonAshton** [comment]
Right, I'll go and give it a go.

**Comment by PrestonAshton** [comment]
All that happens is it flashes the auto focus light when it tries to take a photo...
