### ISSUE TITLE
Nikon Mode cannot be set

### ISSUE THREAD

**Issue by f358183303** [dukus/digiCamControl#144]
Hello, I use your space in making a camera management program, but found Nikon7000 Mode cannot be set ,while other functions in good condition,
Now, I want to know the function takes effect?

**Comment by dukus** [comment]
You should set first the HostMode to true 

For questions about development you can use the application forum http://digicamcontrol.com/phpbb/viewforum.php?f=6&sid=bc81a7e1beaf9009515bdbef1cf09d3b

**Comment by f358183303** [comment]
I'm sorry for i can't open the link . Thanks for your explaination.
In addition, i find the HostMode sometimes be set to false automatically .
Can you tell me What problem caused it?
