### ISSUE TITLE
Stream live view and preview 

### ISSUE THREAD

**Issue by dukus** [dukus/digiCamControl#152]

**Comment by FloBar** [comment]
Hi Duka,
I would be interested in accessing the video stream used in live view mode. My objective would be to extract some frames out of that stream.
Could you please indicate me where I can find it in the code? 
I suppose it must be somewhere within CameraControl/ViewModel/LiveViewViewModel.cs, I am right? 
I also suppose it might be LiveViewData. Is this correct?
Thank you.
