### ISSUE TITLE
Missing 'Stop daily' Time Lapse Feature

### ISSUE THREAD

**Issue by FloBar** [dukus/digiCamControl#162]
Hi Duka,

Sorry for opening a new ticket. However, it would absolutely fantastic if you could add a new feature to stop the time lapse at a specific time every day. This way, it could work in a complementary manner to the existing 'Start daily at' feature.
Thanks a lot.

**Comment by FloBar** [comment]
Hi Dukus,
I have managed to add this feature to the version 1.3.52.
If you are interested, I can share my version with this new feature.
Many thanks.

**Comment by dukus** [comment]
Please share your code

**Comment by FloBar** [comment]
Sure. I uploaded my amended code to: https://github.com/FloBar/digiCamControl
Please refer to Changes_from_original_version.txt for a list of my changes.
