### ISSUE TITLE
Nikon Z6 - LiveViewImageZoomRatio_ValueChanged not working - Included suggested fix

### ISSUE THREAD

**Issue by christianniederm** [dukus/digiCamControl#375]
Hi,

great program. For Nikon Z6 change of LiveViewZoom is not working.
I added **(UInt16)** to Converter.GetBytes in LiveViewImageZoomRatio_ValueChanged in file NikonZ6.cs and now it's working.
Please see below.

Best regards,
Christian

  protected override void LiveViewImageZoomRatio_ValueChanged(object sender, string key, long val)
        {
            lock (Locker)
            {
                SetProperty(CONST_CMD_SetDevicePropValue, BitConverter.GetBytes((UInt16)val),
                            CONST_CMD_LiveViewZoomArea);                
            }
        }

**Comment by dukus** [comment]
Thanks for the feedback
